'use client';

import React, { useEffect, useState } from 'react';
import { formatDateIndian } from '@/utils/dateUtils';
import {
  FileText,
  Search,
  Eye,
  Trash2,
  ExternalLink,
  Loader2,
  CheckCircle,
  AlertTriangle,
} from 'lucide-react';

export default function AdminQuotationsPage() {
  const [loading, setLoading] = useState(true);
  const [quotations, setQuotations] = useState<any[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [success, setSuccess] = useState('');
  const [error, setError] = useState('');

  async function loadQuotations() {
    try {
      const res = await fetch('/api/quotations');
      if (res.ok) {
        const json = await res.json();
        setQuotations(json.quotations || []);
      }
    } catch (err) {
      console.error('Failed to load quotations:', err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadQuotations();
  }, []);

  const handleDelete = async (id: string, code: string) => {
    if (!confirm(`Are you sure you want to delete quotation ${code}? This is irreversible.`)) return;
    setError('');
    setSuccess('');
    try {
      const res = await fetch(`/api/quotations/${id}`, {
        method: 'DELETE',
      });
      if (res.ok) {
        setSuccess(`Quotation ${code} deleted.`);
        await loadQuotations();
      } else {
        throw new Error('Failed to delete quotation.');
      }
    } catch (err: any) {
      setError(err.message || 'An error occurred.');
    }
  };

  const filtered = quotations.filter((q) => {
    const query = searchQuery.toLowerCase();
    return (
      q.quotationNumber.toLowerCase().includes(query) ||
      q.customerName.toLowerCase().includes(query) ||
      (q.customerCompany && q.customerCompany.toLowerCase().includes(query)) ||
      q.rateCardName.toLowerCase().includes(query) ||
      q.userId.toLowerCase().includes(query)
    );
  });

  if (loading) {
    return (
      <div className="min-h-[400px] flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-10 h-10 text-[#1E8262] animate-spin mx-auto mb-3" />
          <p className="text-slate-500 text-xs font-semibold">Loading system quotations...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 w-full font-sans">
      {/* Header */}
      <div className="border-b border-slate-200 pb-4">
        <h1 className="text-xl font-bold text-[#0F4C3A]">Quotation Administration</h1>
        <p className="text-xs text-slate-500 mt-1 font-light">
          Monitor and manage commercial quotations generated by users across the system.
        </p>
      </div>

      {success && (
        <div className="bg-emerald-50 text-emerald-700 border border-emerald-200 p-3 rounded-lg text-xs font-semibold flex items-center gap-2">
          <CheckCircle className="w-4 h-4 text-emerald-600" />
          <span>{success}</span>
        </div>
      )}

      {error && (
        <div className="bg-red-50 text-red-600 border border-red-200 p-3 rounded-lg text-xs font-semibold">
          {error}
        </div>
      )}

      {/* Search Bar */}
      <div className="bg-white border border-slate-200 p-4 rounded-2xl shadow-sm">
        <div className="relative w-full">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
          <input
            type="text"
            placeholder="Search quotations by number, customer, rate card or owner ID..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-slate-50 border border-slate-200 rounded-xl pl-9 pr-4 py-2 text-xs text-slate-700 focus:outline-none focus:bg-white focus:border-[#1E8262] transition"
          />
        </div>
      </div>

      {/* Grid Table */}
      {filtered.length === 0 ? (
        <div className="bg-white border border-slate-200 p-12 text-center rounded-2xl shadow-sm">
          <FileText className="w-12 h-12 text-slate-300 mx-auto mb-3" />
          <h3 className="font-bold text-slate-700 text-sm">No quotations found</h3>
        </div>
      ) : (
        <div className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-x-auto text-xs font-medium text-slate-700">
          <table className="w-full text-left border-collapse min-w-[900px]">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-slate-500 font-bold p-3">
                <th className="p-3.5">Quotation Number</th>
                <th className="p-3.5">User Owner ID</th>
                <th className="p-3.5">Customer Name</th>
                <th className="p-3.5">Route</th>
                <th className="p-3.5 text-right">Amount</th>
                <th className="p-3.5">Rate Card Used</th>
                <th className="p-3.5 text-center">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filtered.map((quote) => (
                <tr key={quote.id} className="hover:bg-slate-50/50">
                  <td className="p-3.5 font-bold text-[#0F4C3A]">
                    {quote.quotationNumber}
                    <span className="block text-[10px] text-slate-400 font-light mt-0.5">
                      Created: {formatDateIndian(quote.createdAt)}
                    </span>
                  </td>
                  <td className="p-3.5 text-slate-500 font-mono text-[11px]">{quote.userId}</td>
                  <td className="p-3.5">
                    <span className="block font-bold text-slate-800">{quote.customerName}</span>
                    <span className="block text-[10px] text-slate-400 font-light">{quote.customerCompany}</span>
                  </td>
                  <td className="p-3.5">
                    <span className="block text-slate-700 font-semibold">{quote.originPincode} → {quote.destinationPincode}</span>
                    <span className="block text-[10px] text-slate-400 font-light">{quote.weight} KG ({quote.pricingMode})</span>
                  </td>
                  <td className="p-3.5 text-right font-black text-slate-900">
                    ₹{quote.totalAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}
                  </td>
                  <td className="p-3.5 text-slate-600 font-semibold">{quote.rateCardName}</td>
                  <td className="p-3.5 text-center flex items-center justify-center gap-1.5">
                    <button
                      onClick={() => window.open(`${window.location.origin}/share/quotations/${quote.id}`, '_blank')}
                      className="p-1.5 hover:bg-slate-100 rounded text-[#1E8262] transition"
                      title="View quotation"
                    >
                      <ExternalLink className="w-4 h-4" />
                    </button>
                    <button
                      onClick={() => handleDelete(quote.id, quote.quotationNumber)}
                      className="p-1.5 hover:bg-slate-100 rounded text-red-500 transition"
                      title="Delete / Revoke Quotation"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
